trigger:
  # start a new build for every push
  batch: False
  branches:
    include:
      - master
      - maintenance/*

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

stages:
- stage: InitialTests
  jobs:
  - job: WindowsFast
    pool:
      vmImage: 'VS2017-Win2016'
    strategy:
      matrix:
          Python36-64bit-fast:
            PYTHON_VERSION: '3.6'
            PYTHON_ARCH: 'x64'
            TEST_MODE: fast
            BITS: 64
    steps:
    - template: azure-steps-windows.yml

- stage: ComprehensiveTests
  jobs:
  - job: Windows
    pool:
      vmImage: 'VS2017-Win2016'
    strategy:
      maxParallel: 6
      matrix:
          Python36-64bit-full:
            PYTHON_VERSION: '3.6'
            PYTHON_ARCH: 'x64'
            TEST_MODE: full
            BITS: 64
          Python37-64bit-full:
            PYTHON_VERSION: '3.7'
            PYTHON_ARCH: 'x64'
            TEST_MODE: full
            BITS: 64
          Python38-64bit-full:
            PYTHON_VERSION: '3.8'
            PYTHON_ARCH: 'x64'
            TEST_MODE: full
            BITS: 64
            NPY_USE_BLAS_ILP64: '1'
            OPENBLAS_SUFFIX: '64_'
    steps:
    - template: azure-steps-windows.yml
